coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
        braces:
            classes_functions:
                class: new-line
                function: new-line
                closure: end-of-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

checks:
    php:
        code_rating: true
        duplication: true
        verify_property_names: true
        uppercase_constants: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        overriding_parameter: true
        optional_parameters_at_the_end: true
        function_in_camel_caps: true
        encourage_single_quotes: true
        classes_in_camel_caps: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        avoid_perl_style_comments: true
        avoid_usage_of_logical_operators: true
        no_exit: false
        no_unnecessary_final_modifier: false
        overriding_private_members: false
        excluded_dependencies:
            - atoum/atoum

build:
    environment:
        php:
            version: 7.0.8
    tests:
#        before:
#            - bin/console doctrine:database:create -n
#            - bin/console doctrine:schema:create -n
#            - bin/console hautelook_alice:doctrine:fixtures:load --purge-with-truncate -n
        override:
            -
                command: 'phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'

filter:
    paths: ["src/"]
    excluded_paths:
        - "*/DataFixtures/*"
